apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .externalSecret.name }}
  namespace: {{ .externalSecret.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-fleet-secrets-manager
  refreshInterval: "1m"
  target:
    name: {{ .externalSecret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "{{ .metadata }}"
      - target: Labels
        literal: "{{ .addons }}"
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: cluster"
      - target: Labels
        literal: "cluster_name: '{{ .cluster_name }}'"
      - target: Labels
        literal: "environment: '{{ .environment }}'"
      data:
        config: "{{ .config }}"
        name: "{{ .cluster_name }}"
        server: "{{ .server }}"
  dataFrom:
    - extract:
        key: {{ .externalSecret.secretManagerSecretName }}