clusterSecretStore:
  namespace: external-secrets
  region: eu-west-1

externalSecret:
  name: ""  # Provide an empty string or a placeholder
  namespace: ""
  secretName: ""
  clusterSecretStore: ""
  secretManagerSecretName: ""
