apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecret.name is required" .Values.externalSecret.name }}
  namespace: {{ required "externalSecret.namespace is required" .Values.externalSecret.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-fleet-secrets-manager
  refreshInterval: "1m"
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "{{`{{ .metadata }}`}}"
      - target: Labels
        literal: "{{`{{ .addons }}`}}"
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: cluster"
      - target: Labels
        literal: "cluster_name: '{{`{{ .cluster_name }}`}}'"
      - target: Labels
        literal: "environment: '{{`{{ .environment }}`}}'"
      data:
        config: "{{`{{ .config }}`}}"
        name: "{{`{{ .cluster_name }}`}}"
        server: {{ if eq .Values.externalSecret.fleetMember "true" }}"https://kubernetes.default.svc"{{ else }}"{{`{{ .server }}`}}"{{ end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretManagerSecretName }}
